[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48082
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Core Command Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-core-command.log'
Level = 'INFO'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'core-metadata.edgex.dev'
  Port = 9999

  [Clients.Logging]
  Protocol = 'http'
  Host = 'support-logging.edgex.dev'
  Port = 9999
