ScheduleInterval = 500

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48085
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-support-scheduler.log'
Level = 'INFO'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'core-metadata.edgex.dev'
  Port = 9999

  [Clients.Logging]
  Protocol = 'http'
  Host = 'support-logging.edgex.dev'
  Port = 9999

[Schedules]
    [Schedules.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Frequency = 'P1D'

[ScheduleEvents]
    [ScheduleEvents.ScrubPushed]
    Name = 'scrub-pushed-events'
    Host = 'core-data.edgex.dev'
    Port = 9999
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'core-data'
    Path = '/api/v1/event/scrub'
    Schedule = 'midnight'
    Scheduler = 'support-scheduler'

    [ScheduleEvents.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'core-data.edgex.dev'
    Port = 9999
    Protocol = 'http'
    Method = 'DELETE'
    Service = 'core-data'
    Path = '/api/v1/event/removeold/age/604800000'
    Schedule = 'midnight'
    Scheduler = 'support-scheduler'





