[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48081
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the EdgeX Core Metadata Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-core-metadata.log'
Level = 'INFO'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'support-logging.edgex.dev'
  Port = 9999
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'support-notifications.edgex.dev'
  Port = 9999

[Databases]
  [Databases.Primary]
  Host = 'mongo.edgex.dev'
  Name = 'metadata'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[Notifications]
PostDeviceChanges = true
Slug = 'device-change-'
Content = 'Device update: '
Sender = 'core-metadata'
Description = 'Metadata device notice'
Label = 'metadata'

